version: "3.7"
services:
  redis:
    image: "redis"
    ports:
      - "6369:6379"

  db:
    image: "postgres"
    restart: "always"
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-securepasswd}"
      POSTGRES_USER: "${POSTGRES_USER:-yo}"
      POSTGRES_DB: "${POSTGRES_DB:-yo}"