-- upgrade --
CREATE TABLE IF NOT EXISTS "category" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
CREATE TABLE IF NOT EXISTS "duration" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
CREATE TABLE IF NOT EXISTS "level" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
CREATE TABLE IF NOT EXISTS "series" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
CREATE TABLE IF NOT EXISTS "teacher" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
CREATE TABLE IF NOT EXISTS "tag" (
    "name" VARCHAR(255) NOT NULL,
    "id" SERIAL NOT NULL PRIMARY KEY
);;
-- downgrade --
DROP TABLE IF EXISTS "category";
DROP TABLE IF EXISTS "duration";
DROP TABLE IF EXISTS "level";
DROP TABLE IF EXISTS "series";
DROP TABLE IF EXISTS "teacher";
DROP TABLE IF EXISTS "tag";
